wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: huggingface
    huggingface_version: 4.17.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.6
    start_time: 1653430345
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      4: 3.7.6
      5: 0.12.16
      6: 4.17.0
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 256
classifier_lr:
  desc: null
  value: 0.01
classifier_weight_decay:
  desc: null
  value: 0
dataset:
  desc: null
  value: cifar100
epochs:
  desc: null
  value: 200
lr:
  desc: null
  value: 0.001
momentum:
  desc: null
  value: 0.9
num_crops_per_aug:
  desc: null
  value:
  - 1
  - 1
num_workers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: LARS
steps:
  desc: null
  value: 39062
transform_kwargs:
  desc: null
  value:
  - brightness: 0.4
    color_jitter_prob: 0.8
    contrast: 0.4
    crop_size: 32
    gaussian_prob: 1.0
    gray_scale_prob: 0.2
    horizontal_flip_prob: 0.5
    hue: 0.1
    max_scale: 1.0
    min_scale: 0.08
    saturation: 0.2
    solarization_prob: 0.0
  - brightness: 0.4
    color_jitter_prob: 0.8
    contrast: 0.4
    crop_size: 32
    gaussian_prob: 0.1
    gray_scale_prob: 0.2
    horizontal_flip_prob: 0.5
    hue: 0.1
    max_scale: 1.0
    min_scale: 0.08
    saturation: 0.2
    solarization_prob: 0.2
warmup_epochs:
  desc: null
  value: 10
warmup_steps:
  desc: null
  value: 1953
wd:
  desc: null
  value: 1.5e-05
weight_decay:
  desc: null
  value: 1.5e-06
